import type { DesignSystemDocKind } from "./design-system-docs";

export type DesignSystemTokenRow = {
  token: string;
  value: string;
  type: "color" | "type" | "spacing" | "radius" | "shadow" | "motion" | "layout";
  scope: "global" | "docs-only" | "case-study";
  usage: string;
  usageZh?: string;
};

export const designPrinciples = [
  "Set the character before adding decoration / 先建立氣質，再談裝飾",
  "Colors can change, the frame cannot fall apart / 顏色可以換，框架不能散",
  "The main actor must always be obvious / 主角永遠要清楚",
  "Interaction is not decoration, it adds meaning / 互動不是加特效，是補語意",
  "High information density still needs room to breathe / 資訊密度高，也要讓人呼吸",
  "Design should be catchable by engineering / 設計要能被工程接住",
  "Every reachable state deserves design attention / 每個可到達狀態都值得被設計",
] as const;

export const designSystemSections = [
  {
    label: "Foundations",
    labelZh: "基礎規範",
    items: ["colors", "typography", "spacing", "radius", "shadows", "motion"].map(
      (slug) => ({ kind: "foundation" as const, slug }),
    ),
  },
  {
    label: "General",
    labelZh: "一般元件",
    items: ["button", "language-switcher"].map((slug) => ({
      kind: "component" as const,
      slug,
    })),
  },
  {
    label: "Shell",
    labelZh: "網站骨架",
    items: ["navbar", "footer"].map((slug) => ({
      kind: "component" as const,
      slug,
    })),
  },
  {
    label: "Navigation",
    labelZh: "導覽",
    items: ["accordion", "tabs", "case-toc"].map((slug) => ({
      kind: "component" as const,
      slug,
    })),
  },
  {
    label: "Data Entry",
    labelZh: "資料輸入",
    items: [
      "floating-input",
      "floating-textarea",
    ].map((slug) => ({ kind: "component" as const, slug })),
  },
  {
    label: "Data Display",
    labelZh: "資料展示",
    items: [
      "project-card",
      "skill-category-card",
      "hero-badge",
    ].map((slug) => ({ kind: "component" as const, slug })),
  },
  {
    label: "Case Study",
    labelZh: "案例頁",
    items: [
      "case-hero",
      "case-section",
      "case-section-header",
      "case-card",
      "case-grid",
      "case-media",
      "case-before-after",
      "before-after-narrative-frame",
      "zoomable-image",
      "flow-scroll-hint",
      "proposal-tabs",
    ].map((slug) => ({ kind: "component" as const, slug })),
  },
  {
    label: "Feedback",
    labelZh: "系統回饋",
    items: ["toast", "modal", "skeleton"].map((slug) => ({
      kind: "component" as const,
      slug,
    })),
  },
  {
    label: "Reference",
    labelZh: "參考資料",
    items: ["tokens", "local-exceptions", "future-backlog"].map((slug) => ({
      kind: "reference" as const,
      slug,
    })),
  },
] satisfies ReadonlyArray<{
  label: string;
  labelZh: string;
  items: ReadonlyArray<{ kind: DesignSystemDocKind; slug: string }>;
}>;

export const designSystemTokenRows = [
  { token: "--hm-purple-50", value: "#f0f1ff", type: "color", scope: "global", usage: "Light purple surface" },
  { token: "--hm-purple-100", value: "#dbdcff", type: "color", scope: "global", usage: "Soft purple background" },
  { token: "--hm-purple-200", value: "#c1c3ff", type: "color", scope: "global", usage: "Purple scale step" },
  { token: "--hm-purple-300", value: "#a1a5f5", type: "color", scope: "global", usage: "Purple scale step" },
  { token: "--hm-purple-400", value: "#8085e8", type: "color", scope: "global", usage: "Purple scale step" },
  { token: "--hm-purple-500", value: "#696edf", type: "color", scope: "global", usage: "Purple scale step" },
  { token: "--hm-purple-600", value: "#5d62d8", type: "color", scope: "global", usage: "Brand purple base" },
  { token: "--hm-purple-700", value: "#4f54c9", type: "color", scope: "global", usage: "Purple hover tone" },
  { token: "--hm-purple-800", value: "#4145a6", type: "color", scope: "global", usage: "Purple dark step" },
  { token: "--hm-purple-900", value: "#363986", type: "color", scope: "global", usage: "Purple darkest step" },
  { token: "--hm-blue-50", value: "#f2f6f9", type: "color", scope: "global", usage: "Blue scale lightest" },
  { token: "--hm-blue-100", value: "#dce5ed", type: "color", scope: "global", usage: "Blue soft background" },
  { token: "--hm-blue-200", value: "#bfd0de", type: "color", scope: "global", usage: "Blue scale step" },
  { token: "--hm-blue-300", value: "#96b2c8", type: "color", scope: "global", usage: "Blue scale step" },
  { token: "--hm-blue-400", value: "#6d91ae", type: "color", scope: "global", usage: "Blue scale step" },
  { token: "--hm-blue-500", value: "#527692", type: "color", scope: "global", usage: "Blue scale step" },
  { token: "--hm-blue-600", value: "#416484", type: "color", scope: "global", usage: "Blue accent base" },
  { token: "--hm-blue-700", value: "#36516b", type: "color", scope: "global", usage: "Blue dark step" },
  { token: "--hm-blue-800", value: "#304657", type: "color", scope: "global", usage: "Blue dark step" },
  { token: "--hm-blue-900", value: "#2b3b49", type: "color", scope: "global", usage: "Blue darkest step" },
  { token: "--hm-green-50", value: "#f1f8f5", type: "color", scope: "global", usage: "Green scale lightest" },
  { token: "--hm-green-100", value: "#d6ebe3", type: "color", scope: "global", usage: "Green soft background" },
  { token: "--hm-green-200", value: "#b0d7c8", type: "color", scope: "global", usage: "Green scale step" },
  { token: "--hm-green-300", value: "#83bba7", type: "color", scope: "global", usage: "Green scale step" },
  { token: "--hm-green-400", value: "#5f9a86", type: "color", scope: "global", usage: "Green scale step" },
  { token: "--hm-green-500", value: "#477a6b", type: "color", scope: "global", usage: "Green accent base" },
  { token: "--hm-green-600", value: "#396458", type: "color", scope: "global", usage: "Green dark step" },
  { token: "--hm-green-700", value: "#315047", type: "color", scope: "global", usage: "Green dark step" },
  { token: "--hm-green-800", value: "#2a413a", type: "color", scope: "global", usage: "Green dark step" },
  { token: "--hm-green-900", value: "#243631", type: "color", scope: "global", usage: "Green darkest step" },
  { token: "--hm-peach-50", value: "#fff6f3", type: "color", scope: "global", usage: "Peach scale lightest" },
  { token: "--hm-peach-100", value: "#fce8e2", type: "color", scope: "global", usage: "Peach soft background" },
  { token: "--hm-peach-200", value: "#f8cfc4", type: "color", scope: "global", usage: "Peach scale step" },
  { token: "--hm-peach-300", value: "#efa995", type: "color", scope: "global", usage: "Peach scale step" },
  { token: "--hm-peach-400", value: "#df795c", type: "color", scope: "global", usage: "Peach scale step" },
  { token: "--hm-peach-500", value: "#c75637", type: "color", scope: "global", usage: "Peach scale step" },
  { token: "--hm-peach-600", value: "#a83b1e", type: "color", scope: "global", usage: "Peach accent base" },
  { token: "--hm-peach-700", value: "#8c301a", type: "color", scope: "global", usage: "Peach dark step" },
  { token: "--hm-peach-800", value: "#742a1b", type: "color", scope: "global", usage: "Peach dark step" },
  { token: "--hm-peach-900", value: "#622719", type: "color", scope: "global", usage: "Peach darkest step" },
  { token: "--hm-brown-50", value: "#f8f6f5", type: "color", scope: "global", usage: "Brown scale lightest" },
  { token: "--hm-brown-100", value: "#e8e2e0", type: "color", scope: "global", usage: "Brown soft background" },
  { token: "--hm-brown-200", value: "#d5c9c5", type: "color", scope: "global", usage: "Brown scale step" },
  { token: "--hm-brown-300", value: "#bba9a3", type: "color", scope: "global", usage: "Brown scale step" },
  { token: "--hm-brown-400", value: "#9c847c", type: "color", scope: "global", usage: "Brown scale step" },
  { token: "--hm-brown-500", value: "#826960", type: "color", scope: "global", usage: "Brown scale step" },
  { token: "--hm-brown-600", value: "#705650", type: "color", scope: "global", usage: "Brown accent base" },
  { token: "--hm-brown-700", value: "#5d4743", type: "color", scope: "global", usage: "Brown dark step" },
  { token: "--hm-brown-800", value: "#4d3c39", type: "color", scope: "global", usage: "Brown dark step" },
  { token: "--hm-brown-900", value: "#413432", type: "color", scope: "global", usage: "Brown darkest step" },
  { token: "--hm-paper", value: "#ffffff", type: "color", scope: "global", usage: "Page background", usageZh: "頁面與卡片底色" },
  { token: "--hm-surface", value: "#f9f9f9", type: "color", scope: "global", usage: "Surface background", usageZh: "輸入框、tab 與柔和 surface 底色" },
  { token: "--hm-ink", value: "#343434", type: "color", scope: "global", usage: "Primary text", usageZh: "主要文字與強層級 UI 文字" },
  { token: "--hm-ink-hover", value: "#555555", type: "color", scope: "global", usage: "Strong hover text" },
  { token: "--hm-muted", value: "#8e8e9c", type: "color", scope: "global", usage: "Muted text", usageZh: "次要按鈕字色與 placeholder" },
  { token: "--hm-line", value: "rgba(0, 0, 0, 0.08)", type: "color", scope: "global", usage: "Default line", usageZh: "輕邊框與分隔線" },
  { token: "--hm-line-strong", value: "rgba(0, 0, 0, 0.16)", type: "color", scope: "global", usage: "Strong line", usageZh: "次要描邊與較強分隔" },
  { token: "--hm-disabled", value: "#dedee4", type: "color", scope: "global", usage: "Disabled fill" },
  { token: "--hm-purple", value: "var(--hm-purple-600)", type: "color", scope: "global", usage: "Brand CTA alias", usageZh: "主要 CTA 與 active 訊號" },
  { token: "--hm-purple-hover", value: "var(--hm-purple-700)", type: "color", scope: "global", usage: "Brand CTA hover alias", usageZh: "主要 CTA hover" },
  { token: "--hm-purple-soft", value: "var(--hm-purple-100)", type: "color", scope: "global", usage: "Brand soft alias", usageZh: "focus ring 與柔和 highlight" },
  { token: "--hm-purple-light", value: "var(--hm-purple-50)", type: "color", scope: "global", usage: "Brand light alias", usageZh: "極淺 hover 面與淡色底" },
  { token: "--hm-blue", value: "var(--hm-blue-600)", type: "color", scope: "global", usage: "Blue accent alias", usageZh: "較沉穩的次重點色" },
  { token: "--hm-blue-soft", value: "var(--hm-blue-100)", type: "color", scope: "global", usage: "Blue soft alias" },
  { token: "--hm-brown", value: "var(--hm-brown-600)", type: "color", scope: "global", usage: "Brown accent alias", usageZh: "偏土色的專案 tone" },
  { token: "--hm-brown-soft", value: "var(--hm-brown-100)", type: "color", scope: "global", usage: "Brown soft alias" },
  { token: "--hm-green", value: "var(--hm-green-500)", type: "color", scope: "global", usage: "Green accent alias", usageZh: "正向與 success 語意色" },
  { token: "--hm-green-soft", value: "var(--hm-green-100)", type: "color", scope: "global", usage: "Green soft alias" },
  { token: "--hm-peach", value: "var(--hm-peach-600)", type: "color", scope: "global", usage: "Peach accent alias", usageZh: "暖色高亮與專案主調" },
  { token: "--hm-peach-soft", value: "var(--hm-peach-100)", type: "color", scope: "global", usage: "Peach soft alias" },
  { token: "--hm-success", value: "#477a6b", type: "color", scope: "global", usage: "Success state" },
  { token: "--hm-success-soft", value: "#d6ebe3", type: "color", scope: "global", usage: "Success soft background" },
  { token: "--hm-warning", value: "#9b6b00", type: "color", scope: "global", usage: "Warning state" },
  { token: "--hm-warning-soft", value: "#fef3c7", type: "color", scope: "global", usage: "Warning soft background" },
  { token: "--hm-error", value: "#b91c1c", type: "color", scope: "global", usage: "Error state" },
  { token: "--hm-error-hover", value: "#991b1b", type: "color", scope: "global", usage: "Error hover state" },
  { token: "--hm-error-soft", value: "#fee2e2", type: "color", scope: "global", usage: "Error soft background" },
  { token: "--hm-info", value: "#1d4ed8", type: "color", scope: "global", usage: "Info state" },
  { token: "--hm-info-soft", value: "#dbeafe", type: "color", scope: "global", usage: "Info soft background" },
  { token: "--cs-accent", value: "var(--hm-purple)", type: "color", scope: "case-study", usage: "Case study primary accent" },
  { token: "--cs-accent-soft", value: "var(--hm-purple-50)", type: "color", scope: "case-study", usage: "Case study soft accent surface" },
  { token: "--cs-surface / --cs-surface-soft", value: "var(--hm-paper) / var(--hm-surface)", type: "color", scope: "case-study", usage: "Case study page and soft surfaces" },
  { token: "--cs-line / --cs-line-strong", value: "var(--hm-line) / var(--hm-line-strong)", type: "color", scope: "case-study", usage: "Case study borders and dividers" },
  { token: "--cs-text-heading / body / muted", value: "var(--text-heading) / var(--text-body) / var(--text-muted)", type: "color", scope: "case-study", usage: "Case study semantic text" },
  { token: "--hm-duration-fast", value: "180ms", type: "motion", scope: "global", usage: "Fast hover and micro-state" },
  { token: "--hm-duration-base", value: "260ms", type: "motion", scope: "global", usage: "Default transition timing" },
  { token: "--hm-duration-slow", value: "420ms", type: "motion", scope: "global", usage: "Longer interface transitions" },
  { token: "--hm-duration-enter", value: "600ms", type: "motion", scope: "global", usage: "Entry animation timing" },
  { token: "--hm-duration-reveal", value: "950ms", type: "motion", scope: "global", usage: "Reveal motion timing" },
  { token: "--hm-ease-standard", value: "ease", type: "motion", scope: "global", usage: "Basic transition easing" },
  { token: "--hm-ease-out", value: "cubic-bezier(0.22, 1, 0.36, 1)", type: "motion", scope: "global", usage: "Calm exit and settle easing" },
  { token: "--hm-ease-emphasized", value: "cubic-bezier(0.215, 0.61, 0.355, 1)", type: "motion", scope: "global", usage: "Emphasized entrance easing" },
  { token: "--hm-space-3xs", value: "4px", type: "spacing", scope: "global", usage: "Micro gap and compact UI spacing" },
  { token: "--hm-space-2xs", value: "8px", type: "spacing", scope: "global", usage: "Tight gap and small list spacing" },
  { token: "--hm-space-xs", value: "12px", type: "spacing", scope: "global", usage: "Compact component padding" },
  { token: "--hm-space-sm", value: "16px", type: "spacing", scope: "global", usage: "Default small spacing" },
  { token: "--hm-space-md", value: "24px", type: "spacing", scope: "global", usage: "Default section-internal spacing" },
  { token: "--hm-space-lg", value: "32px", type: "spacing", scope: "global", usage: "Card and section spacing" },
  { token: "--hm-space-xl", value: "48px", type: "spacing", scope: "global", usage: "Large section spacing" },
  { token: "--hm-space-2xl", value: "64px", type: "spacing", scope: "global", usage: "Major section gap" },
  { token: "--hm-space-3xl", value: "80px", type: "spacing", scope: "global", usage: "Large layout breathing room" },
  { token: "--hm-radius-sm", value: "8px", type: "radius", scope: "global", usage: "Small control radius" },
  { token: "--hm-radius-md", value: "12px", type: "radius", scope: "global", usage: "Default card and input radius" },
  { token: "--hm-radius-lg", value: "16px", type: "radius", scope: "global", usage: "Large panel radius" },
  { token: "--hm-radius-pill", value: "999px", type: "radius", scope: "global", usage: "Badge and pill radius" },
  { token: "--hm-radius-button", value: "200px", type: "radius", scope: "global", usage: "Button-specific pill radius" },
  { token: "--hm-container", value: "1440px", type: "layout", scope: "global", usage: "Default content container width" },
  { token: "--hm-container-wide", value: "1920px", type: "layout", scope: "global", usage: "Wide content container width" },
  { token: "--hm-grid-gutter", value: "24px", type: "layout", scope: "global", usage: "Standard grid gutter" },
  { token: "--hm-grid-gutter-lg", value: "32px", type: "layout", scope: "global", usage: "Large grid gutter" },
  { token: "--hm-z-base", value: "0", type: "layout", scope: "global", usage: "Base stacking layer" },
  { token: "--hm-z-sticky", value: "10", type: "layout", scope: "global", usage: "Sticky elements" },
  { token: "--hm-z-navbar", value: "100", type: "layout", scope: "global", usage: "Navbar layer" },
  { token: "--hm-z-overlay", value: "200", type: "layout", scope: "global", usage: "Overlay layer" },
  { token: "--hm-z-modal", value: "300", type: "layout", scope: "global", usage: "Modal layer" },
  { token: "--hm-z-toast", value: "400", type: "layout", scope: "global", usage: "Toast layer" },
  { token: "--hm-bp-mobile", value: "768px", type: "layout", scope: "docs-only", usage: "Mobile breakpoint reference" },
  { token: "--hm-bp-tablet", value: "1024px", type: "layout", scope: "docs-only", usage: "Tablet breakpoint reference" },
  { token: "--hm-bp-desktop", value: "1440px", type: "layout", scope: "docs-only", usage: "Desktop breakpoint reference" },
  { token: "--hm-chart-1", value: "#416484", type: "color", scope: "global", usage: "Chart palette 1" },
  { token: "--hm-chart-2", value: "#477a6b", type: "color", scope: "global", usage: "Chart palette 2" },
  { token: "--hm-chart-3", value: "#a83b1e", type: "color", scope: "global", usage: "Chart palette 3" },
  { token: "--hm-chart-4", value: "#705650", type: "color", scope: "global", usage: "Chart palette 4" },
  { token: "--hm-chart-5", value: "#7c3aed", type: "color", scope: "global", usage: "Chart palette 5" },
  { token: "--hm-chart-6", value: "#0f766e", type: "color", scope: "global", usage: "Chart palette 6" },
  { token: "--fs-h1", value: "32px / 24px / 22px", type: "type", scope: "global", usage: "Page main heading" },
  { token: "--fs-h2", value: "28px / 22px / 20px", type: "type", scope: "global", usage: "Section heading" },
  { token: "--fs-h3", value: "24px / 18px / 16px", type: "type", scope: "global", usage: "Card heading" },
  { token: "--fs-h4", value: "18px / 16px / 14px", type: "type", scope: "global", usage: "Subheading" },
  { token: "--fs-body", value: "16px", type: "type", scope: "global", usage: "Body text" },
  { token: "--fs-sm", value: "14px", type: "type", scope: "global", usage: "Small labels" },
  { token: "--fs-xs", value: "12px", type: "type", scope: "global", usage: "Tiny helper copy" },
  { token: "--shadow-sm", value: "0 2px 8px rgba(0, 0, 0, 0.06)", type: "shadow", scope: "global", usage: "Light card lift" },
  { token: "--shadow-md", value: "0 10px 20px rgba(0, 0, 0, 0.12)", type: "shadow", scope: "global", usage: "Medium elevation" },
  { token: "--shadow-lg", value: "0 10px 40px rgba(0, 0, 0, 0.12)", type: "shadow", scope: "global", usage: "Large panel shadow" },
  { token: "--shadow-xl", value: "0 40px 80px rgba(0, 0, 0, 0.25)", type: "shadow", scope: "global", usage: "Very high elevation" },
  { token: "--shadow-card-hover", value: "0 16px 32px rgba(0, 0, 0, 0.16)", type: "shadow", scope: "global", usage: "Project card hover" },

  { token: "--text-heading", value: "#1a1a1a", type: "color", scope: "global", usage: "Project tone alias", usageZh: "頁面大標與區塊標題" },
  { token: "--text-body", value: "#1f2933", type: "color", scope: "global", usage: "Project tone alias", usageZh: "內文" },
  { token: "--text-secondary", value: "#5d6674", type: "color", scope: "global", usage: "Project tone alias", usageZh: "說明文字與輔助 label" },
  { token: "--text-muted", value: "#8e8e9c", type: "color", scope: "global", usage: "Project tone alias", usageZh: "最弱層級文字" },
  { token: ".tone-advantech --tag-text", value: "#004b85", type: "color", scope: "global", usage: "Project tone alias", usageZh: "Advantech 標籤文字" },
  { token: ".tone-advantech --tag-bg", value: "#d9f1ff", type: "color", scope: "global", usage: "Project tone alias", usageZh: "Advantech 標籤底色" },
  { token: ".tone-laushu --tag-text", value: "#3b3475", type: "color", scope: "global", usage: "Project tone alias", usageZh: "Laushu 標籤文字" },
  { token: ".tone-laushu --tag-bg", value: "#f5eeff", type: "color", scope: "global", usage: "Project tone alias", usageZh: "Laushu 標籤底色" },
] satisfies DesignSystemTokenRow[];
